image_corner_intensity:
  type: "string"
  default: "10px"
  description: 'Change this value to increase or decrease border rounding'
image_border_width:
  type: "string"
  default: "0px"
  description: 'Add a border e.g. 2px - default OFF = 0px)'
image_border_color:
  type: "string"
  default: "#9A9A9A"
  description: 'Set the color if you enabled border width'

onebox_corner_intensity:
  type: "string"
  default: "10px"
  description: 'Change this value to increase or decrease border rounding'
onebox_border_width:
  type: "string"
  default: ""
  description: 'Change onebox border width e.g. 5px'
onebox_border_color:
  type: "string"
  default: "var(--primary-low)"
  description: 'Change color for onebox borders e.g. #000000'
onebox_background_color:
  type: "string"
  default: "var(--secondary)"
  description: 'Change color for onebox backgound e.g. #000000'

topic_thumbnail_list_rounded_corners:
  type: "string"
  default: "10px"
  description: 'Change this value to increase or decrease border rounding'

topic_thumbnail_list_placeholder_bg:
  type: "string"
  default: "var(--primary-low)"
  description: 'Change color for onebox backgound e.g. #000000'