Corner_intensity:
  type: "string"
  default: "10px"
  description: 'Change this value to increase or decrease border rounding'
Border_width:
  type: "string"
  default: "0px"
  description: 'Add a border e.g. 2px - default OFF = 0px)'
Border_color:
  type: "string"
  default: "#9A9A9A"
  description: 'Set the color if you enabled border width'

Onebox_corner_intensity:
  type: "string"
  default: "10px"
  description: 'Change this value to increase or decrease border rounding'
Onebox_border_color:
  type: "string"
  default: "var(--primary-low)"
  description: 'Change color for onebox borders e.g. #000000'
Onebox_background_color:
  type: "string"
  default: "var(--secondary)"
  description: 'Change color for onebox backgound e.g. #000000'