Corner_intensity:
  type: "string"
  default: "10px"
  description: 'Change this value to increase or decrease border rounding'
Border_width:
  type: "string"
  default: "0px"
  description: 'Add a border e.g. 2px - default off (0px)'
Border_color:
  type: "string"
  default: "#9A9A9A"
  description: 'Set the color if you enabled border width'